version: '3'
services:
  postgresql:
    image: "postgres:13.1"
    restart: always
    environment:
      POSTGRES_USER: khoadt
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: kong
    ports:
      - 5432:5432
    volumes:
      - database:/var/bin/postgresql
  redis:
    container_name: dxg-redis
    restart: always
    image: redis:6.2.5
    ports:
      - '6379:6379'

volumes:
  database: