
server:
  port: 9002

#config database
spring:
  datasource:
    password: zkU4xyjQNLCTO4EcllgmQfyOWPyeuFS1
    url: jdbc:postgresql://dpg-cml5bl2cn0vc739natag-a.singapore-postgres.render.com:5432/user_y053?currentSchema=course
    username: khoadamtam
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
      type: TRACE

#config s3
amazon:
  s3:
    bucket: khoadt2001-1002
    region:  us-east-1
    id: AKIARW2U6OGRNZ36AUVB
    access_key: 5GyN+5Nu9g94y0Y2sFGfczDp7Ni2crevF/kmZpl3
spring.servlet.multipart.max-file-size: 1000MB
spring.servlet.multipart.max-request-size: 1000MB

kong:
  api-key: JPrxbq2bbX6nJTJbu7INIameRUH6dRZn


#config azure
azure:
  storage:
    container:
      name: course
    file-share:
      name: english-app
    connection:
      string: DefaultEndpointsProtocol=https;AccountName=englishappone;AccountKey=7pbtKhYvhuHj1jdKUCtXDKz+xEduFyfHgKOxLUo517mXJYR/PWVsNRJlgBuHnAXZhEaaZt9l77+E+AStIp9NMQ==;EndpointSuffix=core.windows.net