socket-server:
  port: 9008
  host: localhost

server:
  port: 9998

spring:
  datasource:
    password: zkU4xyjQNLCTO4EcllgmQfyOWPyeuFS1
    url: jdbc:postgresql://dpg-cml5bl2cn0vc739natag-a.singapore-postgres.render.com:5432/user_y053?currentSchema=english-app
    username: khoadamtam
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  redis:
    host: redis-10190.c281.us-east-1-2.ec2.cloud.redislabs.com
    port: 10190
    havePassword: YES
    username: default
    password: qNv8n4MafaURVPDZ03kaT5f1aWdTGZC4
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: d180a2c1fdb7f14108e1
            client-secret: 6144aea24b43dcda66725c3a02b2f4665977d26f
          google:
            client-id: 701424571214-ma0tka7ntifmjvel7eocob775thbkkjg.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 3345241832432650
            client-secret: 74dae8859a9acee9f44c60dcd94f402b
            scope:
              - email
              - public_profile
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/v18.0/me?fields=name_format,id,email,first_name,middle_name,last_name,name,verified,picture.width(250).height(250)


#thoi gian cua token la 3h
secret:
  key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDjrOOSzmnZkvqyTMj79MWRr15Q4fSdottj53i3WgUONNsglt5zdH0XMCYo9YqcrWorzleuuVn1XFoX+ujZolY9dRPz93JeCLJSnHzOAS+/UFO1iCu4kTAdQW32ME2vbmqhf4MYlVcDRdd8V/dOODHzd0bHjqMGR5Hglbf9v8oZQIDAQAB
  time_live: 18000000


kong:
  gateway:
    port: 8000
    host: http://localhost
    checkHost: NO
  fe:
    port: 5173
    host: http://localhost
    checkHost: NO
  url:
    create-user: http://localhost:8000/api/user/save-or-update
  api-key: u28ioA0jsgAbgLqVSNZ5I90lJPMgzcki