server:
  port: 9000

kafka:
  properties:
    bootstrap:
      servers: localhost:9092
  gateway:
    group_id: englist-socket

spring:
  profiles:
    active: local
  kafka:
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: manual


